name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: go run . --target Build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeamsBarHider
          path: TeamsBarHider.zip
